name: weather_app
description: App to display weather from different places.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.12.2
  weather: ^1.2.4
  geolocator: ^5.3.1
  intl: ^0.16.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1 

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"

flutter:

  
  uses-material-design: true

  
  assets:
    - images/

  
